### ISSUE TITLE
Important Add-On, but lack of elegance...

### ISSUE THREAD

**Issue by ruixiangTan** [tcrespog/vlc-subtitle-word-search#1]
Have you tried Potplayer before, it has word in subtitle searching feather, simply pause the play, click on the word in the subtitle, then Chrome or Firefox opened with the searching result..

**Comment by tcrespog** [comment]
Hi, ruixiangTan.
Thanks for the information, I didn't know about Potplayer, seems interesting, but as I can see it only works for Windows.
Unfortunately, the same functionality you mentioned can't be achieved in VLC with the current extension support. There is an existing extension that does a similar thing but it relies on the keyboard to select a word instead of on mouse clicks, you can check it [here](http://addons.videolan.org/content/show.php/Dico?content=141904).

**Comment by ruixiangTan** [comment]
Hi,

Thank you for your kind reply. Personally, I believe the best way to learn
the meaning of a word is through Images, let's say we want to know the
meaning of the word "Laser", we could search Google Images, Laser Images
https://www.google.com/search?tbm=isch&source=hp&biw=406&bih=527&q=Laser,
then the meaning is clear. Besides, we could query other popular websites
such as Vocabulary.com https://www.vocabulary.com/dictionary/laser to get
the pronunciation and store the word in a list for later review.

The online word search feature in Potplayer does exactly the same, but in a
simple way, when we encounter a new word during a movie, we pause the play,
the player parses the subtitle str by space, then we click the word we want
to know the meaning, the player seems replace the "%%$$" in the query
string with the word we clicked on and open the predefined website.

Thank you again for your recommendation.

**Comment by tcrespog** [comment]
I agree with the image-based learning process too :smiley:.
This extension allows you to open the search links in the browser too in order to view the full-fledged web result page there.

It's a pity that the Potplayer's way can't be implemented using the Lua extension mechanism provided by VLC, but VLC extensions have been old-fashioned for years now and the support for advanced features is limited and it's even [regressing](https://trac.videolan.org/vlc/ticket/8097#comment:15).

Anyway I encourage you to study some way to bring that feature to VLC, it would be wonderful!

Thank you for the feedback :wink:.
