### ISSUE TITLE
Doesn't display the text areas in the GUI

### ISSUE THREAD

**Issue by rodrigopolo** [tcrespog/vlc-subtitle-word-search#15]
Using Version 3.0.20 Vetinari (Apple Silicon) on macOS Sonoma 14.2.1 (23C71), it doesn't diplay the text areas in the GUI:
![gui](https://github.com/tcrespog/vlc-subtitle-word-search/assets/1511174/1ba68e7b-0d0e-420c-bac3-6e3fb4bbbf73)

**Comment by tcrespog** [comment]
Hi, @rodrigopolo. Thanks for reporting.

Unfortunately I don't own a Mac to try. Does it happen just for this extension? Or does it happen for others too? For example, the "VLsub" extension is usually installed by default and includes a text box too.

![image](https://github.com/tcrespog/vlc-subtitle-word-search/assets/10177888/54bdb1ab-2515-4083-936f-eb04f3ee7e29)

**Comment by rodrigopolo** [comment]
The `VLsub` plugin works as expected:
![VLsub](https://github.com/tcrespog/vlc-subtitle-word-search/assets/1511174/edd3117a-7b10-4efd-b51a-0ab3e8156120)

**Comment by tcrespog** [comment]
I've been able to reproduce the issue using a macOS 14 virtual machine. I'll debug it in the following days.

**Comment by tcrespog** [comment]
It turns out the text box was actually there, but its colour is the same as the background (this is the way VLC renders that kind of component in MacOS 14). In [v1.6](https://github.com/tcrespog/vlc-subtitle-word-search/releases/tag/v1.6), I've added a default text to help avoiding confusion.

![Screenshot_20240120_182318](https://github.com/tcrespog/vlc-subtitle-word-search/assets/10177888/354c1196-03a3-4d9a-94f0-3e393945aacf)
