### ISSUE TITLE
Bug: the main menu item of the extension stops working after the extension window is closed

### ISSUE THREAD

**Issue by milichev** [tcrespog/vlc-subtitle-word-search#9]
### Steps to reproduce

1. Open the extension using the main menu item (View -> Subtitle Word Search);
2. When the extension window appears, close it with its corner Close button.
    * The window closes.
3. Click the main menu item, as described in step 1.

### Expected behavior

The extension window appears again

### Actual behavior

The extension window never shows up, unless the VLC app is relaunched.

**Comment by tcrespog** [comment]
Hi, @milichev.

As far as I can see, this happens when opening, closing and re-opening the extension while there's no video playing. In other words:

1. Open VLC (do not open a video file).
2. Open the extension.
3. Close the extension dialog.
4. Try to open the extension again.
5. The dialog doesn't open.

Is that the case for you too?

By the way, thank you for all the suggestions.

**Comment by milichev** [comment]
@tcrespog , exactly, your steps are correct. Thanks!
